<?php

namespace AppBundle\Repository;

/**
 * DistributionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DistributionRepository extends \Doctrine\ORM\EntityRepository
{
	
	public function getRetailersViaDistribution($region) {
		$query = $this->createQueryBuilder('d')
			->join('d.retail', 'r');
			
			If ($region!='all'){
				$query=$query->where('d.county = :parameter')
				->setParameter('parameter', $region);
			}
			$query = $query->groupBy('r.farmer')
			->getQuery();

		return $query->getResult();
	}

}
