<?php

namespace AppBundle\Repository;

/**
 * FrenchGeoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FrenchGeoRepository extends \Doctrine\ORM\EntityRepository
{
		public function getFrenchRegions(){
			
			$query = $this->createQueryBuilder('fg')
			->select('DISTINCT fg.region')
			->orderBy('fg.region', 'ASC')
			->getQuery();

		return $query->getResult();
			
		}
}
