<?php

namespace AppBundle\Repository;

/**
 * OpenHoursRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OpenHoursRepository extends \Doctrine\ORM\EntityRepository
{
}
