<?php

namespace AppBundle\Repository;

/**
 * RetailRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RetailRepository extends \Doctrine\ORM\EntityRepository
{
}
