<?php

namespace AppBundle\Repository;

/**
 * WeekdaysRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WeekdaysRepository extends \Doctrine\ORM\EntityRepository
{
}
